### ISSUE TITLE
string_view: No such file or directory

### ISSUE THREAD

**Issue by mjhram** [ghlin/ygopro-replay-inflate#1]
HI,
I am trying to compile the project using make, but I got error:

```
compile(g++) - ../src/app.cc
In file included from ../src/support/file-io.h:3:0,
                 from ../src/app.cc:1:
../src/support/../prelude.h:23:23: fatal error: string_view: No such file or directory
compilation terminated.
Makefile:28: recipe for target 'objs/___src__app.o' failed
make: *** [objs/___src__app.o] Error 1
```
it seems that string_view is not recognized by g++. Can you please let me know your build environment.

**Comment by ghlin** [comment]
My GCC version is `8.2.1`.

This project is writing in c++17. Any compiler supports c++17 would be able to compile it.

But the card information might be out-dated (this demo reads card data from the file `from-sqlite3.json` which is dumped from YGOPRO's [`cards.cdb`](https://github.com/moecube/ygopro-database)). As a result, replay file contains newer cards won't be translated, I'll fix it ASAP.

**Comment by mjhram** [comment]
Thanks. I installed g++ v7 and now it passes this point. Now I have error about lua: 
```
compile(g++) - ../src/3rd-part/core/ocgapi.cpp
In file included from ../src/3rd-part/core/ocgapi.cpp:15:0:
../src/3rd-part/core/interpreter.h:17:10: fatal error: lua.h: No such file or directory
 #include <lua.h>
          ^~~~~~~
compilation terminated.
Makefile:142: recipe for target 'objs/___src_3rd-part_core__ocgapi.o' failed
make: *** [objs/___src_3rd-part_core__ocgapi.o] Error 1

```

How can I make the compiler finds Lua header and library files?

**Comment by mjhram** [comment]
Now, I could build the project successfully.
