### ISSUE TITLE
issue with some replay file

### ISSUE THREAD

**Issue by mjhram** [ghlin/ygopro-replay-inflate#2]
Hi,
After building the project, I tried converting some replay files, but for some files it exits with error:
```
$ replay-inflate my1.yrp -p /home/mjhram/Desktop/ygopro -o my1.json
[ERROR] load_from_static_storage: unknown code 700000003
terminate called after throwing an instance of 'std::runtime_error'
  what():  load_from_static_storage: unknonw code
Aborted (core dumped)

```
following are 2 replay files that didn't work:
[replay files.zip](https://github.com/ghlin/ygopro-replay-inflate/files/2553467/replay.files.zip)

one of them, I download it from internet, the other one I generate it from "YGOPRO Down of a New Era"

**Comment by ghlin** [comment]
(Thanks for playing with my project :smile:

I checked your replay files, both of the two replay contains _custom cards_(cards not released by KONAMI but created by players) which are not included in your ygopro's card database(`cards.cdb`) and script library(`script` + `expansions` folder).

It is impossible to translate such replay without having the modified version of ygopro(which generates that replaly file).

(the error message is not so user-friendly, sorry for that

**Comment by mjhram** [comment]
You are right. The AI deck was custom deck. It is clear now.
Thanks.
